# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
wdir: "/vol/cloud/agnostos-wf/db_creation"
rdir: "/vol/cloud/agnostos_test/db_creation"
data: "/vol/cloud/agnostos_test/db_creation_data" # rename your data to match the format "{sample_name}_contigs.fasta"
# choose a name for your dataset
data_name: "tara_039_041"

conda_env: "/vol/cloud/agnostos-wf/envs/workflow.yml"
# Threads configuration
threads_default: 28
threads_collect: 28
threads_cat_ref: 4
# Databases
pfam_db: "/vol/cloud/agnostos-wf/databases/Pfam-A.hmm"
pfam_clan: "/vol/cloud/agnostos-wf/databases/Pfam-A.clans.tsv.gz"
antifam_db: "/vol/cloud/agnostos-wf/databases/AntiFam.hmm"
uniref90_db: "/vol/cloud/agnostos-wf/databases/uniref90.db"
nr_db: "/vol/cloud/agnostos-wf/databases/nr.db"
uniclust_db: "/vol/cloud/agnostos-wf/databases/uniclust30_2018_08/uniclust30_2018_08"
#uniprot_db: "/vol/cloud/agnostos-wf/databases/uniprotKB.fasta.gz"
pfam_hh_db: "/vol/cloud/agnostos-wf/databases/pfam"
DPD: "/vol/cloud/agnostos-wf/databases/dpd_uniprot_sprot.fasta.gz"
db_dir: "/vol/cloud/agnostos-wf/databases/"
taxdb: "/vol/cloud/agnostos-wf/databases/uniprotKB"
gtdb_tax: "/vol/cloud/agnostos-wf/databases/gtdb-r89_54k/gtdb-r89_54k.fmi"
# Files retrieved from the databases
# List of shared reduced Pfam domain names (dowloadable from Figshare..)
pfam_shared_terms: "/vol/cloud/agnostos-wf/databases/Pfam-31_names_mod_01122019.tsv"
# Created using the protein accessions and the descriptions found on the fasta headers
uniref90_prot: "/vol/cloud/agnostos-wf/databases/uniref90.proteins.tsv.gz"
nr_prot: "/vol/cloud/agnostos-wf/databases/nr.proteins.tsv.gz"
# Information dowloaded from Dataset-S1 from the DPD paper:
dpd_info: "/vol/cloud/agnostos-wf/databases/dpd_ids_all_info.tsv.gz"

# Local template folder
local_tmp: "/vol/scratch/tmp"

# MPI runner (de.NBI cloud, SLURM)
mpi_runner: "srun --mpi=pmi2"

#vmtouch for the DBs
vmtouch: "vmtouch"

# Gene prediction
prodigal_mode: "meta" #"meta" for metagenomes or "normal" for genomes
prodigal_bin: "prodigal"

# Annotation
hmmer_bin: "/vol/cloud/agnostos-wf/bin/hmmsearch"

# Clustering config
ffindex_apply: "/vol/cloud/agnostos-wf/bin/ffindex_apply_mpi"
mmseqs_bin: "/vol/cloud/agnostos-wf/bin/mmseqs"
mmseqs_tmp: "/vol/cloud/agnostos-wf/tmp"
mmseqs_local_tmp: "/vol/scratch/tmp"
mmseqs_split_mem: "100G"
mmseqs_split: 10

# Clustering results config
seqtk_bin: "seqtk"

# Spurious and shadows config
hmmpress_bin: "/vol/cloud/agnostos-wf/bin/hmmpress"

# Compositional validation config
datamash_bin: "datamash"
famsa_bin: "/vol/cloud/agnostos-wf/bin/famsa"
odseq_bin: "/vol/cloud/agnostos-wf/bin/OD-seq"
leonbis_bin: "/vol/cloud/agnostos-wf/bin/leon-bis.tcsh"
parasail_bin: "/vol/cloud/agnostos-wf/bin/parasail_aligner"
parallel_bin: "parallel"
get_stats: "/vol/cloud/agnostos-wf/db_creation/scripts/get_stats.r"
isconn: "/vol/cloud/agnostos-wf/db_creation/scripts/is_connected"
filterg: "/vol/cloud/agnostos-wf/db_creation/scripts/filter_graph"
igraph_lib: "export LD_LIBRARY_PATH=/vol/cloud/agnostos-wf/bin/igraph/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
parasail_lib: "export LD_LIBRARY_PATH=/vol/cloud/agnostos-wf/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# Cluster classification config
seqkit_bin: "seqkit"
filterbyname: "filterbyname.sh"
hhcons_bin: "/vol/cloud/agnostos-wf/bin/hh-suite/bin/hhconsensus"

# Cluster category refinement
hhsuite: "/vol/cloud/agnostos-wf/bin/hh-suite"
hhblits_bin_mpi: "/vol/cloud/agnostos-wf/bin/hh-suite/bin/hhblits_mpi"
hhmake: "/vol/cloud/agnostos-wf/bin/hh-suite/bin/hhmake"
hhblits_prob: 90
hypo_filt: 1.0

# Taxonomy
kaiju_bin: "/vol/cloud/agnostos-wf/bin/kaiju"

# Cluster communities
hhblits_bin: "/vol/cloud/agnostos-wf/bin/hh-suite/bin/hhblits"
hhsearch_bin: "/vol/cloud/agnostos-wf/bin/hh-suite/bin/hhsearch"
